# DataSource Config
spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1/loach?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1/loach?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: loach
    password: loach

mybatis-plus:
  mapper-locations: classpath*:/mapper/user/*.xml
